# @package _global_

# python train.py exp=diff_lat_txt_0
scratch_dir: ./scratch
#device: [0]
num_workers: 12
batch_size: 8

sampling_rate: 48000
length: 2097152
channels: 2
log_every_n_steps: 1000
ckpt_every_n_steps: 5000

module:
  _target_: module.Module
  lr: 1e-4
  lr_beta1: 0.95
  lr_beta2: 0.999
  lr_eps: 1e-6
  lr_weight_decay: 1e-3
  ema_beta: 0.995
  ema_power: 0.7
  embedding_mask_proba: 0.1
  autoencoder_name: dmae1d-ATC64-v4

  model:
    _target_: audio_diffusion_pytorch.models.DiffusionModel
    in_channels: 32
    dim: 1 
    channels: [128, 256, 512, 512, 1024, 1024]
    factors: [1, 2, 2, 2, 2, 2]
    items: [2, 2, 2, 4, 8, 8]
    attentions: [0, 0, 1, 1, 1, 1]
    cross_attentions: [1, 1, 1, 1, 1, 1]
    attention_heads: 12
    attention_features: 64
    embedding_max_length: 64
    embedding_features: 768
    use_text_conditioning: True 
    use_embedding_cfg: True 

datamodule:
  num_workers: ${num_workers}
  dataset_train:
    path: ../../classical_music_data_3/train_data.json
    batch_size: ${batch_size}
  dataset_valid:
    path: ../../classical_music_data_4/train_data.json
    batch_size: ${batch_size}

callbacks:
  rich_progress_bar:
    _target_: pytorch_lightning.callbacks.RichProgressBar

  model_checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    save_last: True 
    dirpath: ./outputs
    every_n_train_steps: ${ckpt_every_n_steps}

  model_summary:
    _target_: pytorch_lightning.callbacks.RichModelSummary
    max_depth: 2

  audio_samples_logger:
    _target_: logger.SampleLogger
    num_items: 3
    channels: ${channels}
    sampling_rate: ${sampling_rate}
    sampling_steps: [10, 50]
    decoder_sampling_steps: 50 
    embedding_scale: 5.0 
    use_ema_model: False

loggers:
  wandb:
    _target_: pytorch_lightning.loggers.wandb.WandbLogger
    project: mousai
    entity: kamalojasv
    # offline: False  # set True to store all logs only locally
    job_type: "train"
    group: ""
    save_dir: ./scratch

trainer:
  _target_: pytorch_lightning.Trainer
  precision: 32 # Precision used for tensors, default `32`
  accelerator: gpu 
  devices: -1
  num_nodes: 16
  strategy: ddp_find_unused_parameters_true
  min_epochs: 0
  max_epochs: -1
  enable_model_summary: False
  log_every_n_steps: 1 # Logs metrics every N batches
  limit_val_batches: 10 
  check_val_every_n_epoch: null
  val_check_interval: ${log_every_n_steps}
  # default_root_dir: s3://s-harmonai/flavio/ckpts/${now:%Y-%m-%d-%H-%M-%S}/
