device: cuda
mulan_path: output/music-lm/mulan/wandb/latest-run/files/best_model.pt

semantic_transformer:
  dim: 1024
  depth: 12

coarse_transformer:
  dim: 1024
  depth: 12
  num_coarse_quantizers: 3
  codebook_size: 1024

fine_transformer:
  num_coarse_quantizers: 3
  num_fine_quantizers: 5
  dim: 1024
  depth: 12
  codebook_size: 1024

soundstream:
  rq_num_quantizers: 8
  rq_groups: 2
  attn_window_size: 128
  attn_depth: 2
  grad_accum_every: 1

train_audios_folder: ../../data/data

batch_size: 16
data_max_length_seconds: 2
num_train_steps: 100000
data_max_length: 320*32
